// Supabase database operations for support tickets
import { supabase } from '../lib/supabase';
import { calculateTicketPriority } from './reportPriority';

/**
 * Create a new support ticket
 * @param {Object} ticketData - Ticket data
 * @returns {Promise<Object>} - Created ticket
 */
export const createTicket = async (ticketData) => {
    try {
        // Calculate priority
        const priority = calculateTicketPriority(ticketData);

        // Insert ticket (ticket_number will be auto-generated by trigger)
        const { data, error } = await supabase
            .from('support_tickets')
            .insert([{
                ...ticketData,
                priority
            }])
            .select()
            .single();

        if (error) throw error;

        return { success: true, data };
    } catch (error) {
        console.error('Error creating ticket:', error);
        return { success: false, error: error.message };
    }
};

/**
 * Get tickets by user
 * @param {string} userId - User ID
 * @param {Object} filters - Filter options { status, category, limit, offset }
 * @returns {Promise<Array>} - List of tickets
 */
export const getTicketsByUser = async (userId, filters = {}) => {
    try {
        let query = supabase
            .from('support_tickets')
            .select(`
        *,
        user:user_id(id, username, avatar_url, email),
        assigned_admin:assigned_to(id, username)
      `)
            .eq('user_id', userId)
            .order('created_at', { ascending: false });

        // Apply filters
        if (filters.status) {
            query = query.eq('status', filters.status);
        }

        if (filters.category) {
            query = query.eq('category', filters.category);
        }

        if (filters.limit) {
            query = query.limit(filters.limit);
        }

        if (filters.offset) {
            query = query.range(filters.offset, filters.offset + (filters.limit || 10) - 1);
        }

        const { data, error } = await query;

        if (error) throw error;

        return { success: true, data };
    } catch (error) {
        console.error('Error fetching user tickets:', error);
        return { success: false, error: error.message, data: [] };
    }
};

/**
 * Get admin ticket queue
 * @param {Object} filters - Filter options { status, priority, category, assigned_to, limit, offset }
 * @returns {Promise<Array>} - List of tickets
 */
export const getTicketQueue = async (filters = {}) => {
    try {
        let query = supabase
            .from('support_tickets')
            .select(`
        *,
        user:user_id(id, username, avatar_url, email, trust_score),
        assigned_admin:assigned_to(id, username, avatar_url)
      `)
            .order('created_at', { ascending: false });

        // Apply filters
        if (filters.status) {
            query = query.eq('status', filters.status);
        }

        if (filters.priority) {
            query = query.eq('priority', filters.priority);
        }

        if (filters.category) {
            query = query.eq('category', filters.category);
        }

        if (filters.assigned_to) {
            query = query.eq('assigned_to', filters.assigned_to);
        }

        if (filters.limit) {
            query = query.limit(filters.limit);
        }

        if (filters.offset) {
            query = query.range(filters.offset, filters.offset + (filters.limit || 50) - 1);
        }

        const { data, error } = await query;

        if (error) throw error;

        return { success: true, data };
    } catch (error) {
        console.error('Error fetching ticket queue:', error);
        return { success: false, error: error.message, data: [] };
    }
};

/**
 * Get ticket by ID with all messages
 * @param {string} ticketId - Ticket ID
 * @returns {Promise<Object>} - Ticket with messages
 */
export const getTicketById = async (ticketId) => {
    try {
        // Get ticket
        const { data: ticket, error: ticketError } = await supabase
            .from('support_tickets')
            .select(`
        *,
        user:user_id(id, username, avatar_url, email),
        assigned_admin:assigned_to(id, username, avatar_url)
      `)
            .eq('id', ticketId)
            .single();

        if (ticketError) throw ticketError;

        // Get messages
        const { data: messages, error: messagesError } = await supabase
            .from('support_ticket_messages')
            .select(`
        *,
        sender:sender_id(id, username, avatar_url)
      `)
            .eq('ticket_id', ticketId)
            .order('created_at', { ascending: true });

        if (messagesError) throw messagesError;

        return {
            success: true,
            data: {
                ...ticket,
                messages: messages || []
            }
        };
    } catch (error) {
        console.error('Error fetching ticket:', error);
        return { success: false, error: error.message };
    }
};

/**
 * Add message to ticket
 * @param {Object} messageData - { ticket_id, sender_id, message, attachments, is_admin, is_internal_note }
 * @returns {Promise<Object>} - Created message
 */
export const addTicketMessage = async (messageData) => {
    try {
        const { data, error } = await supabase
            .from('support_ticket_messages')
            .insert([messageData])
            .select(`
        *,
        sender:sender_id(id, username, avatar_url)
      `)
            .single();

        if (error) throw error;

        // Update ticket's updated_at
        await supabase
            .from('support_tickets')
            .update({ updated_at: new Date().toISOString() })
            .eq('id', messageData.ticket_id);

        return { success: true, data };
    } catch (error) {
        console.error('Error adding ticket message:', error);
        return { success: false, error: error.message };
    }
};

/**
 * Update ticket status
 * @param {string} ticketId - Ticket ID
 * @param {Object} updateData - { status, priority, assigned_to }
 * @returns {Promise<Object>} - Updated ticket
 */
export const updateTicketStatus = async (ticketId, updateData) => {
    try {
        const updates = {
            ...updateData,
            updated_at: new Date().toISOString()
        };

        if (updateData.status === 'resolved' || updateData.status === 'closed') {
            updates.resolved_at = new Date().toISOString();
        }

        const { data, error } = await supabase
            .from('support_tickets')
            .update(updates)
            .eq('id', ticketId)
            .select()
            .single();

        if (error) throw error;

        return { success: true, data };
    } catch (error) {
        console.error('Error updating ticket status:', error);
        return { success: false, error: error.message };
    }
};

/**
 * Get unread message count for ticket
 * @param {string} ticketId - Ticket ID
 * @param {string} userId - User ID
 * @param {boolean} isAdmin - Whether user is admin
 * @returns {Promise<number>} - Unread count
 */
export const getUnreadCount = async (ticketId, userId, isAdmin = false) => {
    try {
        let query = supabase
            .from('support_ticket_messages')
            .select('*', { count: 'exact', head: true })
            .eq('ticket_id', ticketId);

        // User sees unread admin messages
        if (!isAdmin) {
            query = query.eq('is_admin', true).neq('sender_id', userId);
        } else {
            // Admin sees unread user messages
            query = query.eq('is_admin', false).neq('sender_id', userId);
        }

        const { count, error } = await query;

        if (error) throw error;

        return count || 0;
    } catch (error) {
        console.error('Error getting unread count:', error);
        return 0;
    }
};

/**
 * Search tickets
 * @param {string} searchQuery - Search query
 * @param {Object} filters - Additional filters
 * @returns {Promise<Array>} - Matching tickets
 */
export const searchTickets = async (searchQuery, filters = {}) => {
    try {
        let query = supabase
            .from('support_tickets')
            .select(`
        *,
        user:user_id(id, username, avatar_url, email)
      `)
            .or(`subject.ilike.%${searchQuery}%,description.ilike.%${searchQuery}%,ticket_number.ilike.%${searchQuery}%`)
            .order('created_at', { ascending: false });

        // Apply additional filters
        if (filters.status) {
            query = query.eq('status', filters.status);
        }

        if (filters.limit) {
            query = query.limit(filters.limit);
        }

        const { data, error } = await query;

        if (error) throw error;

        return { success: true, data };
    } catch (error) {
        console.error('Error searching tickets:', error);
        return { success: false, error: error.message, data: [] };
    }
};

/**
 * Subscribe to ticket updates (real-time)
 * @param {string} ticketId - Ticket ID
 * @param {Function} onUpdate - Callback when ticket updates
 * @returns {Object} - Subscription object
 */
export const subscribeToTicket = (ticketId, onUpdate) => {
    const subscription = supabase
        .channel(`ticket-${ticketId}`)
        .on(
            'postgres_changes',
            {
                event: '*',
                schema: 'public',
                table: 'support_ticket_messages',
                filter: `ticket_id=eq.${ticketId}`
            },
            onUpdate
        )
        .subscribe();

    return subscription;
};

export default {
    createTicket,
    getTicketsByUser,
    getTicketQueue,
    getTicketById,
    addTicketMessage,
    updateTicketStatus,
    getUnreadCount,
    searchTickets,
    subscribeToTicket
};
